= Pre-Authentication
:toc:
:toc-placement!:

toc::[]

== Authentication via HTTP headers

On the former security-proxy, there was a mechanism called "SP-trust-SP"
which basically allowed to leave the authentication and authorization
to another component placed before the security-proxy. The authentication
would then be performed by using HTTP headers.

The gateway implements a similar feature, and this can be activated
by configuring the gateway using the following:

```yaml
georchestra:
  gateway:
    headerAuthentication: true
```

The following headers are expected to be received by the Gateway:

* `sec-georchestra-preauthenticated`: set to `true`
* `sec-username`: set to the username / user identifier (e.g. "pmauduit")
* `sec-email`: the email address of the user (e.g. "pierre.mauduit@example.org")
* `sec-firstname`: the first name of the user (e.g. "Pierre")
* `sec-lastname`: the surname of the user (e.g. "Mauduit")
* `sec-org`: the organisation identifier (e.g. "geOrchestra")

== Account creation

In order to be able to administer users who are using the pre-authentication mechanism,
an account is created into the geOrchestra OpenLDAP, if available in the gateway configuration.

The account creation must be explicitly activated using the following yaml configuration:

```
georchestra:
  gateway:
    headerAuthentication: true
    security:
      createNonExistingUsersInLDAP: true
```

To create the user into the geOrchestra LDAP, a `default` LDAP must be
defined, and you generally need read/write access to it. Below is a configuration example
suitable for your `application.yml` gateway configuration file:

```
georchestra:
  gateway:
    security:
      ldap:
        default:
          enabled: true
          extended: true
          url: ldap://georchestra-ldap:389/
          baseDn: dc=georchestra,dc=org
          adminDn: cn=admin,dc=georchestra,dc=org
          adminPassword: secret
          users:
            rdn: ou=users
            searchFilter: (uid={0})
            pendingUsersSearchBaseDN: ou=pendingusers
            protectedUsers: geoserver_privileged_user
          roles:
            rdn: ou=roles
            searchFilter: (member={0})
            protectedRoles: ADMINISTRATOR, EXTRACTORAPP, GN_.*, ORGADMIN, REFERENT, USER, SUPERUSER
          orgs:
            rdn: ou=orgs
            orgTypes: Association,Company,NGO,Individual,Other
            pendingOrgSearchBaseDN: ou=pendingorgs
```

== Security considerations

As the HTTP headers can be controlled by the remote user issuing the query, it is *mandatory* to have your gateway inaccessible directly ; on such setup, it must be placed behind another proxy component which will take care of sanitizing the incoming requests.

You can find a documented configuration sample of an Apache webserver which makes use of the `mod_mellon` to interact with the Renater federation.

== Renater configuration sample

The following Apache configuration has been used in a setup to interact with the Renater federation:

```
<VirtualHost *:80>
      ServerName https://georchestra.example.org:443/
      UseCanonicalName On

      ServerAdmin webmaster@localhost
      DocumentRoot /var/www/html

      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Location />
        MellonEnable "info"
        MellonSecureCookie On
        MellonUser eppn
        MellonMergeEnvVars On
        MellonSubjectConfirmationDataAddressCheck Off

        # These have been generated by the mellon_create_metadata script and provided to Renater
        MellonSPPrivateKeyFile  /etc/apache2/mellon/https_poc_renater.inrae.sandbox.apps.gs_fr_prod.camptocamp.com_.key
        MellonSPCertFile        /etc/apache2/mellon/https_poc_renater.inrae.sandbox.apps.gs_fr_prod.camptocamp.com_.cert
        MellonSPentityId        <renater-entity-id>
        MellonOrganizationName "ORG"
        MellonOrganizationURL "https://example.org"

        # This file is downloaded from the Renater Federation, and has to be kept up to date
        MellonIdPMetadataFile /etc/apache2/mellon/preview-idps-test-metadata.xml
        MellonDiscoveryURL    https://discovery.renater.fr/test/WAYF?cru=yes

        # These files are also available on the Internet on https://metadata.federation.renater.fr/certs/
        MellonIdPCAFile        "/etc/apache2/mellon/renater-metadata-signing-cert-2016.pem"
        MellonIdPPublicKeyFile "/etc/apache2/mellon/renater-metadata-signing-cert-2016.pem"

        MellonProbeDiscoveryTimeout 1
        MellonSetEnv "MAIL" "urn:oid:0.9.2342.19200300.100.1.3"
        MellonSetEnv "EPPN" "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
        MellonSetEnv "CN" "urn:oid:2.5.4.3"
        MellonSetEnv "O" "urn:oid:2.5.4.10"
        MellonSetEnv "SN" "urn:oid:2.5.4.4"
        MellonSetEnv "GIVEN_NAME" "urn:oid:2.5.4.42"

        MellonEndpointPath /mellon

        # it is this proxy's responsability to make sure the value of these headers are legit
        # See a list of headers used by geOrchestra here:
        # https://github.com/georchestra/georchestra/blob/master/commons/src/main/java/org/georchestra/commons/security/SecurityHeaders.java#L41-L67
        RequestHeader unset sec-georchestra-preauthenticated
        RequestHeader unset sec-mellon-name-id
        RequestHeader unset sec-username
        RequestHeader unset sec-longname
        RequestHeader unset sec-name
        RequestHeader unset sec-givenname
        RequestHeader unset sec-email
        RequestHeader unset sec-org
        RequestHeader unset sec-proxy
        RequestHeader unset sec-user
        RequestHeader unset sec-organization
        RequestHeader unset sec-userid
        RequestHeader unset sec-lastupdated
        RequestHeader unset sec-roles
        RequestHeader unset sec-firstname
        RequestHeader unset sec-lastname
        RequestHeader unset sec-tel
        RequestHeader unset sec-orgid
        RequestHeader unset sec-orgname
        RequestHeader unset sec-org-lastupdated
        RequestHeader unset imp-roles
        RequestHeader unset imp-username

        RequestHeader set sec-georchestra-preauthenticated true "expr=-n env('MELLON_NAME_ID')"
        RequestHeader set sec-mellon-name-id %{MELLON_NAME_ID}e "expr=-n env('MELLON_NAME_ID')"
        RequestHeader set sec-username %{MELLON_EPPN}e "expr=-n env('MELLON_EPPN')"
        RequestHeader set sec-longname %{MELLON_CN}e "expr=-n env('MELLON_CN')"
        RequestHeader set sec-name %{MELLON_SN}e "expr=-n env('MELLON_SN')"
        RequestHeader set sec-firstname %{MELLON_GIVEN_NAME}e "expr=-n env('MELLON_GIVEN_NAME')"
        RequestHeader set sec-email %{MELLON_MAIL}e "expr=-n env('MELLON_MAIL')"
        RequestHeader set sec-org %{MELLON_O}e "expr=-n env('MELLON_O')"

        ProxyPass "http://georchestra-gateway-svc:8080/"
        ProxyPassReverse "http://georchestra-gateway-svc:8080/"
        ProxyPreserveHost On
    </Location>

    <Location /login/renater>
        AuthType Mellon
        MellonEnable auth
        Require valid-user
        Redirect "/"
    </Location>

</VirtualHost>
```

You can see that Apache is taking care of sanitizing the request with the multiple calls to `RequestHeader unset` before
setting them to a value provided by the `mod_mellon` if available, else they are kept unset.

The second `Location` allows to trigger an authentication when hitting the `/login/renater` endpoint, which is linked
onto a custom login page of the gateway.

